apiVersion: backup.oiler.backup/v1
kind: BackupRequest
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprequest-sample
spec:
  dbSpec:
    uri: "10.100.159.91"
    port: 3306
    user: "testuser"
    pass: "testpassword"
    dbName: "testdb"
    dbType: "mysql"
  s3Spec:
    endpoint: "https://10.109.69.152:443"
    bucketName: "testdb"
    auth:
      accessKey: "9sDY9Qog7WQGMLrzqXIT"
      secretKey: "KwvkghK4CiTmhfRm5vcMPxumUWIRuZmqS2ccJhYW"
  schedule: "*/1 * * * *"
  maxBackupCount: 2
