apiVersion: backup.oiler.backup/v1
kind: BackupRequest
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprequest-sample
spec:
  dbSpec:
    uri: "postgres.default.svc.cluster.local"
    port: 5432
    user: "admin"
    pass: "password"
    dbName: "mydatabase"
    dbType: "postgres"
  s3Spec:
    endpoint: "https://minio.tenant-ns.svc.cluster.local:443"
    bucketName: "test"
    auth:
      accessKey: "14PcLhk3HKXJ3Jdq88Vg"
      secretKey: "eOAAaPLoJ0RevDmmcj6gS4fjPbTz1iqrBt7dm2Id"
  schedule: "*/1 * * * *"
  maxBackupCount: 2
