apiVersion: backup.oiler.backup/v1
kind: BackupRestore
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprestore-sample
spec:
  dbSpec:
    uri: "mongodb-service.default.svc.cluster.local"
    port: 27017
    user: "root"
    pass: "root"
    dbName: "admin"
    dbType: "mongodb"
  s3Spec:
    endpoint: "https://minio.minio-tenant.svc.cluster.local"
    bucketName: "testdb"
    auth:
      accessKey: "9sDY9Qog7WQGMLrzqXIT"
      secretKey: "KwvkghK4CiTmhfRm5vcMPxumUWIRuZmqS2ccJhYW"
  backupRevision: "0"
