apiVersion: backup.oiler.backup/v1
kind: BackupRestore
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprestore-sample
spec:
  dbUri: "mongodb-service.default.svc.cluster.local"
  databasePort: 27017
  databaseUser: "root"
  databasePass: "root"
  databaseName: "admin"
  databaseType: "mongodb"
  s3Endpoint: "https://minio.minio-tenant.svc.cluster.local"
  s3AccessKey: "9sDY9Qog7WQGMLrzqXIT"
  s3SecretKey: "KwvkghK4CiTmhfRm5vcMPxumUWIRuZmqS2ccJhYW"
  # s3AccessKey: minio
  # s3SecretKey: minio123
  s3BucketName: testdb
  backupRevision: "0"
