apiVersion: backup.oiler.backup/v1
kind: BackupRequest
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprequest-sample
spec:
  dbUri: "postgres.svc.cluster.local"
  databasePort: 5432
  databaseUser: "admin"
  databasePass: "password"
  databaseName: "mydatabase"
  databaseType: "postgres"
  schedule: "*/1 * * * *"
  storageClass: "s3"
  s3Endpoint: "https://minio.tenant-ns.svc.cluster.local:443"
  s3AccessKey: 14PcLhk3HKXJ3Jdq88Vg
  s3SecretKey: eOAAaPLoJ0RevDmmcj6gS4fjPbTz1iqrBt7dm2Id
  maxBackupCount: 2
  s3BucketName: test
