apiVersion: backup.oiler.backup/v1
kind: BackupRestore
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprestore-sample
spec:
  dbUri: "10.107.243.182"
  databasePort: 27017
  databaseUser: "root"
  databasePass: "root"
  databaseName: "admin"
  databaseType: "mongodb"
  s3Endpoint: "https://10.109.69.152:443"
  s3AccessKey: "u82r7zETfISCUoiF26lW"
  s3SecretKey: "oMGiH3XwzygOGgK0NskgLOiZX8KARJ1G7OClrcdm"
  # s3AccessKey: minio
  # s3SecretKey: minio123
  s3BucketName: testdb
  backupRevision: "1"
