apiVersion: backup.oiler.backup/v1
kind: BackupRestore
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprestore-sample
spec:
  dbUri: "10.100.159.91"
  databasePort: 3306
  databaseUser: "testuser"
  databasePass: "testpassword"
  databaseName: "testdb"
  databaseType: "mysql"
  s3Endpoint: "https://10.109.69.152:443"
  s3AccessKey: 9sDY9Qog7WQGMLrzqXIT
  s3SecretKey: KwvkghK4CiTmhfRm5vcMPxumUWIRuZmqS2ccJhYW
  # s3AccessKey: minio
  # s3SecretKey: minio123
  s3BucketName: testdb
  backupRevision: '0'
