# This rule is not used by the project oiler-backup itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to backup.oiler.backup resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprestore-viewer-role
rules:
- apiGroups:
  - backup.oiler.backup
  resources:
  - backuprestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.oiler.backup
  resources:
  - backuprestores/status
  verbs:
  - get
