{
 "title": "Backup Operator",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query_0",
    "label": "backup_entity",
    "query": {
     "query": "label_values(backup_duration_seconds_bucket{backup_name=\"$query_0\"},backup_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Successful Backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_requests_successful_total{backup_name=~\"$query_0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_requests_failed_total{backup_name=~\"$query_0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Duration Buckets",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_duration_seconds_bucket{backup_name=~\"$query_0\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Successful Backup Recoveries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_restores_successful_total{restore_name=~\"$query_0.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Backup Recoveries ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_restores_failed_total{restore_name=~\"$query_0.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Recovery Duration Buckets",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_duration_seconds_bucket{backup_name=~\"$query_0\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}